Grad clip patch for megatron v2.2
laekov/fastmoe pull request #65
Opened 2021-07-30 06:40 UTC by laekov

2021-07-30 06:40 UTC, laekov commented
#29

2021-07-30 15:05 UTC, xptree requested changes
see my detailed comments below.

2021-07-30 15:05 UTC, xptree commented on examples/megatron/clip-grad-v2.2.patch
> ++            torch.distributed.all_reduce(grad_norm)
it seems that we need to reduce the square of norm, because:

||x||_2^2 = (x_1^2 + x_2^2) +  (x_3^2 + x_4^2)

2021-08-02 05:47 UTC, xptree approved these changes
LGTM

2021-08-02 05:50 UTC, merged